# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        features: ["unix", "windows"]
        # Exclude invalid combinations
        exclude:
          - os: ubuntu-latest
            features: windows
          - os: macos-latest
            features: windows
          - os: windows-latest
            features: unix
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build
        run: cargo build --verbose --no-default-features --features ${{ matrix.features }}

      - name: Run tests
        run: cargo test --verbose --no-default-features --features ${{ matrix.features }}