# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: rust-lang/rustup@v1
        with:
          toolchain: stable

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Build
        run: cargo build --verbose --no-default-features --features ${{ matrix.features }}
      - name: Test
        run: cargo test --verbose --no-default-features --features ${{ matrix.features }}