name: Enforce PR Labels

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Labels
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          REPO="${{ github.repository }}"

          LABELS=$(curl -s -H "Authorization: token $GH_TOKEN" \
            "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/labels" | jq -r '.[].name')

          # Required labels
          REQUIRED_LABELS=("minor" "major" "patch")

          # Check if PR contains at least one required label
          for label in "${REQUIRED_LABELS[@]}"; do
            if echo "$LABELS" | grep -q "$label"; then
              echo "✅ PR has a valid label ($label)."
              exit 0
            fi
          done

          echo "❌ ERROR: PR must have one of the following labels: minor, major, patch."
          exit 1

      - name: Auto-Comment on PR if Missing Labels
        if: failure()
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          REPO="${{ github.repository }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          COMMENT="⚠️ **PR Validation Failed**: This PR is missing a required label. Please add one of: **minor, major, patch**."
          API_URL="https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments"

          echo "Posting comment to $API_URL"

          curl -s -H "Authorization: token $GH_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               -X POST \
               -d "{\"body\":\"$COMMENT\"}" \
               "$API_URL"